import "@/styles/globals.css";
import { Inter } from "next/font/google";
import NavWrapper from "@/components/NavWrapper";
import { CursorGradient } from "@/components/CursorGradient";
import { cn } from "@/lib/utils";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn("min-h-screen font-sans bg-background leading-relaxed text-foreground antialiased selection:bg-secondary selection:text-secondary-foreground transition-all duration-300 ease-in-out", inter.variable)}>
        <CursorGradient />
        <NavWrapper />
        <main className="flex flex-col items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
